<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="page-header">
    <h1>
        Search contactDetailsCompany
    </h1>
    <p>
        <?php echo $this->tag->linkTo(["contactDetailsCompany/new", "Create contactDetailsCompany"]) ?>
    </p>
</div>

<?php echo $this->getContent() ?>

<?php
    echo $this->tag->form(
        [
            "contactDetailsCompany/search",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldCompanyid" class="col-sm-2 control-label">CompanyId</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["companyId", "type" => "number", "class" => "form-control", "id" => "fieldCompanyid"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFax" class="col-sm-2 control-label">Fax</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fax", "size" => 30, "class" => "form-control", "id" => "fieldFax"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWebsite" class="col-sm-2 control-label">WebSite</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["webSite", "size" => 30, "class" => "form-control", "id" => "fieldWebsite"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Search", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
