<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["contactDetailsCompany/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["contactDetailsCompany/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CompanyId</th>
            <th>Email</th>
            <th>Fax</th>
            <th>WebSite</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $contactDetailsCompany): ?>
            <tr>
                <td><?php echo $contactDetailsCompany->getCompanyid() ?></td>
            <td><?php echo $contactDetailsCompany->getEmail() ?></td>
            <td><?php echo $contactDetailsCompany->getFax() ?></td>
            <td><?php echo $contactDetailsCompany->getWebsite() ?></td>

                <td><?php echo $this->tag->linkTo(["contactDetailsCompany/edit/" . $contactDetailsCompany->getCompanyid(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["contactDetailsCompany/delete/" . $contactDetailsCompany->getCompanyid(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("contactDetailsCompany/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("contactDetailsCompany/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("contactDetailsCompany/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("contactDetailsCompany/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
