version: '3'
services:
  php:
    build: ./php
    ports:
      - 8080:80
    restart: always
    volumes: 
      - "./site:/var/www/html"
  composer: 
    image: composer
    volumes: 
      - "./site:/var/www/html"
    working_dir: "/var/www/html"
    command: composer install
#  nginx:
#    build: ./nginx
#    ports:
#      - 8080:80
#    restart: always
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_PASSWORD: example