version: '3'
services:
  php:
    build: ./php
    ports:
      - 8080:80
    restart: always
    volumes: 
      - "./site:/var/www/html"
#  composer: 
#    image: composer
#    volumes: 
#      - "./site:/var/www/html"
#    working_dir: "/var/www/html"
#    command: composer install
#  db:
#    image: postgres
#    restart: always
#    ports:
#      - 5432:5432
#    volumes:
#      - ./db:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: bro4you_ru
#      POSTGRES_PASSWORD: bro4you_ru
#      POSTGRES_DB: bro4you_ru