##  based on Ubuntu 18.04
### Linux Apach Postgres Php
##  7.12.18         by Sergo
# --------------------------
# web 
#     localhost:8081
# db 
#     port::5433 
#     user::docker 
#     password::docker

version: '3'

services:

  apache:
    build: ${MY_CONTAINERS}/apache
    volumes: 
      - ${MY_PHP_LOGS}:${DC_PHP_LOGS}
      - ${MY_SITES}:${DC_SITES}/
    ports:
      - 8081:80
      
  postgresql: 
    build: ${MY_CONTAINERS}/postgresql
    volumes: 
      - ${MY_DB_LOGS}:${DC_DB_LOGS}
      - ${MY_DB_DUMP}:${DC_DB_DUMP}
    ports:
      - 5433:5432
  
  composer: 
    image: composer
    volumes: 
      - ${MY_SITES}/${MY_BACKEND}:${DC_SITES}/${MY_BACKEND}
    working_dir: ${DC_SITES}/${MY_BACKEND}
    command: composer install