<?php
$this->assets->outputCss();
?>

    <div class="tr-breadcrumb5 bg-image section-before">
        <div class="container">
            <div class="breadcrumb-info text-center">
                <div class="user-title">
                    <h1> Чат </h1>
                </div>
                <ul class="job-meta tr-list list-inline">
                </ul>
            </div>
        </div><!-- /.container -->
    </div><!-- /.tr-breadcrumb -->

    <div class="col-12">
    <div class="card">
    <div class="card-body">
<?= $this->getContent() ?>
<!--
    <ul class="tr-list account-details">
    <div class="jqte_editor" id="edit" contenteditable="false">
        <li>ФИО<span></span></li>

        <li>Адрес<span></span></li>
        <li>Дата рождения<span></span></li>
        <li>Пол<span>?></span></li>

        <li>О себе<span></span></li>
    </div>
    </ul>
-->


<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Название</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['name', 'size' => 50, 'class' => 'form-control', 'id' => 'fieldName', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategoryid" class="col-sm-2 control-label">Категория</label>
    <div class="col-sm-10">
        <?= $this->tag->select(['categoryId', $categories, 'using' => ['categoryId', 'categoryName'], 'class' => 'form-control', 'id' => 'fieldCategoryid', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Описание</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['description', 'size' => 1000, 'class' => 'form-control', 'id' => 'fieldDescription', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldaddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['address', 'size' => 100, 'class' => 'form-control', 'id' => 'fieldaddress', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDeadline" class="col-sm-2 control-label">Дата работ</label>
    <div class="col-sm-10">
        <?= $this->tag->dateTimeLocalField(['deadline', 'class' => 'form-control', 'id' => 'fieldDeadline', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Стоимость</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['price', 'type' => 'numeric', 'class' => 'form-control', 'id' => 'fieldPrice', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatestart" class="col-sm-2 control-label">Дата начала тендера</label>
    <div class="col-sm-10">
        <?= $this->tag->dateTimeLocalField(['dateStart', 'class' => 'form-control', 'id' => 'fieldDatestart', 'readonly' => 'true']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateend" class="col-sm-2 control-label">Дата окончания тендера</label>
    <div class="col-sm-10">
        <?= $this->tag->dateTimeLocalField(['dateEnd', 'class' => 'form-control', 'id' => 'fieldDateend', 'readonly' => 'true']) ?>
    </div>
</div>

        <div class="section display-information">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Чат</h4>
                        <h6 class="card-subtitle">С Петров Александр </h6>
                        <div class="chat-box">
                            <!--chat Row -->
                            <ul class="chat-list">
                                <!--chat Row -->
                                <li>
                                    <div class="chat-img"><img src="/img/b0460072.jpg" alt="user" /></div>
                                    <div class="chat-content">
                                        <h5>Темчишен Андрей</h5>
                                        <div class="box bg-light-info">Спасибо, что откликнулись</div>
                                    </div>
                                    <div class="chat-time">10:56 </div>
                                </li>
                                <!--chat Row -->
                                <li>
                                    <div class="chat-img"><img src="/img/b0460072.jpg" alt="user" /></div>
                                    <div class="chat-content">
                                        <h5>Темчишен Андрей</h5>
                                        <div class="box bg-light-info">Вас всё устраивает?</div>
                                    </div>
                                    <div class="chat-time">10:57 </div>
                                </li>
                                <!--chat Row -->
                                <li class="reverse">
                                    <div class="chat-content">
                                        <h5>Петров Александр</h5>
                                        <div class="box bg-light-inverse">Да</div>
                                    </div>
                                    <div class="chat-img"><img src="/img/perepechko.jpg" alt="user" /></div>
                                    <div class="chat-time">10:57 </div>
                                </li>
                                <!--chat Row -->
                                <li class="reverse">
                                    <div class="chat-content">
                                        <h5>Петров Александр</h5>
                                        <div class="box bg-light-inverse">Все хорошо, сделаю в лучшем виде</div>
                                    </div>
                                    <div class="chat-img"><img src="/img/perepechko.jpg" alt="user" /></div>
                                    <div class="chat-time">10:57 </div>
                                </li>
                                <!--chat Row -->
                                <li>
                                    <div class="chat-img"><img src="/img/b0460072.jpg" alt="user" /></div>
                                    <div class="chat-content">
                                        <h5>Темчишен Андрей</h5>
                                        <div class="box bg-light-info">Отлично!</div>
                                    </div>
                                    <div class="chat-time">11:00 am</div>
                                </li>
                                <!--chat Row -->
                            </ul>
                        </div>
                    </div>
                    <div class="card-body b-t">
                        <div class="row">
                            <div class="col-8">
                                <textarea placeholder="Type your message here" class="form-control b-0"></textarea>
                            </div>
                            <div class="col-4 text-right">
                                <button type="button" class="btn btn-info btn-circle btn-lg"><i class="fa fa-paper-plane-o"></i> </button>
                            </div>
                        </div>
                    </div>
                    <?php
                    echo $this->tag->form(
                        [
                            "coordination/end",
                            "autocomplete" => "off",
                            "class" => "form-horizontal"
                        ]
                    );
                    ?>

                    <?= $this->tag->hiddenField(['auctionId']) ?>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <?php echo $this->tag->submitButton(["Завершить задание", "class" => "btn btn-primary"]) ?>
                        </div>
                    </div>
                    <?php echo $this->tag->endForm(); ?>
                </div>
        </div>


        <?= $this->tag->hiddenField(['id']) ?>
<!--
<div id = "chat" class="layer">
    <table class="table-hover">
        <tbody>
        <?php foreach ($messages as $message): ?>
            <tr>
                <td class="with-background"><?php
                    if($message->getInput() != $owner)
                        echo 'Вы: ' . $message->getMessage() . ' (' .$message->getDate().')';
                    ?></td>
                <td class="with-background"><?php
                    if($message->getInput() == $owner)
                        echo  $otherUser->Userinfo->getFirstname() .' ' . $otherUser->Userinfo->getLastname() . ': '
                            .  $message->getMessage() . ' (' .$message->getDate().')';
                    ?></td>

            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<script type="text/javascript">
    var block = document.getElementById("chat");
    block.scrollTop = block.scrollHeight;
    //$("div.chat").scrollTop = $("div.chat").scrollHeight;
</script>

<?php
    echo $this->tag->form(
        [
            "coordination/create",
            "autocomplete" => "off",
            "class" => "form-horizontal"
        ]
    );
?>



<div class="form-group">
    <div class="col-sm-10">
        <?php echo $this->tag->textArea(["message", "cols" => 30, "rows" => 4, "class" => "form-control", "id" => "fieldMessage"]) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Отправить", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>

<?php
echo $this->tag->form(
    [
        "coordination/end",
        "autocomplete" => "off",
        "class" => "form-horizontal"
    ]
);
?>

<?= $this->tag->hiddenField(['auctionId']) ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Завершить задание", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?> -->
    </div>
    </div>
    </div>
