<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?= $this->tag->linkTo(['messages', 'Назад']) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Изменение сообщения
    </h1>
</div>

<?= $this->getContent() ?>

<?= $this->tag->form(['messages/save', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>

<div class="form-group">
    <label for="fieldAuctionid" class="col-sm-2 control-label">ID аукциона</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['auctionId', 'type' => 'numeric', 'class' => 'form-control', 'id' => 'fieldAuctionid']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldInput" class="col-sm-2 control-label">Тип сообщения</label>
    <div class="col-sm-10">
        <?= $this->tag->selectStatic(['input', ['1' => 'От исполнителя', '0' => 'От заказчика'], 'class' => 'form-control', 'id' => 'fieldInput']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMessage" class="col-sm-2 control-label">Текст сообщения</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['message', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldMessage']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDate" class="col-sm-2 control-label">Дата и время отправки</label>
    <div class="col-sm-10">
        <?= $this->tag->DateTimeLocalField(['date', 'class' => 'form-control', 'id' => 'fieldDate']) ?>
    </div>
</div>


<?= $this->tag->hiddenField(['messageId']) ?>

<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->tag->submitButton(['Изменить', 'class' => 'btn btn-default']) ?>
    </div>
</div>

</form>
