
<div class="tr-breadcrumb4 bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="user-title">
                <h1>Создать предложение</h1>
            </div>

        </div>
    </div><!-- /.container -->
</div><!-- /.tr-breadcrumb -->

<div class="tr-profile section-padding">
    <div class="container">
        <div class="row">
            <div class=" col-md-12">

<?= $this->getContent() ?>

<?= $this->tag->form(['offers/create', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>

<div class="form-group">
    <label for="fieldDescriptionOffer" class="col-sm-2 control-label">Описание</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['descriptionOffer', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldDescription']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDeadlineOffer" class="col-sm-2 control-label">Срок выполнения</label>
    <div class="col-sm-10">
        <?= $this->tag->dateTimeLocalField(['deadlineOffer', 'class' => 'form-control', 'id' => 'fieldDeadline']) ?>
    </div>
</div>



<div class="form-group">
    <label for="fieldPriceOffer" class="col-sm-2 control-label">Стоимость</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['priceOffer', 'type' => 'numeric', 'class' => 'form-control', 'id' => 'fieldPrice']) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->tag->submitButton(['Добавить', 'class' => 'btn btn-primary']) ?>
    </div>
</div>

</form>
            </div>
        </div>
    </div>

</div>