
<?= $this->getContent();
$this->assets->outputCss();?>

<!--
<div class="page-header">
    <h1>
        Созданные задания
    </h1>
    <p> <?= $this->tag->linkTo(['tasks/new', 'Создать задание']) ?></p>
    <p> <?= $this->tag->linkTo(['tasks/mytasks/' . $userId, 'Мои задания']) ?></p>
    <p>  <?= $this->tag->linkTo(['offers/myoffers/' . $userId, 'Мои предложения']) ?></p>
    <p>  <?= $this->tag->linkTo(['tasks/doingtasks/' . $userId, 'Мне выполняют задания']) ?></p>
    <p>  <?= $this->tag->linkTo(['tasks/workingtasks/' . $userId, 'Мои выполняемые задания']) ?></p>
</div>-->


<div class="tr-breadcrumb2 bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="page-title">
                <h1>Список заданий</h1>
            </div>
        </div>
    </div><!-- /.container -->
</div>


    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                        <thead>
                        <tr>
                            <th class="footable-sortable">№<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Название<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Категория<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Описание<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Адрес<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Дата работ<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Стоимость<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Статус<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable" colspan="2">Действия<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Тендер/Чат<span class="footable-sort-indicator"></span></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $count=1; if (isset($page->items)) { ?>
                        <?php foreach ($page->items as $task) { ?>
                        <tr>
                            <td><?=$count++; $count; ?></td>
                            <td><?= $this->tag->linkTo(['auctions/show/' . $task->getTaskid(), $task->getName()]) ?></td>
                            <td><?= $task->categories->getCategoryName() ?></td>
                            <td><?= $task->getDescription() ?></td>
                            <td><?= $task->getaddress() ?></td>
                            <td><?= date('h:m d.m.Y',strtotime($task->getDeadline())) ?></td>
                            <td><?= $task->getPrice() ?></td>
                            <td><?= $task->getStatus() ?></td>
                            <td><?= $this->tag->linkTo(['tasks/editing/' . $task->getTaskid(), '<i class="fa fa-pencil text-inverse m-r-10"></i>']) ?></td>
                            <td><?= $this->tag->linkTo(['tasks/delete/' . $task->getTaskid(), '<i class="fa fa-close text-danger"></i>']) ?></td>
                            <?php if ($task->status == 'Поиск') { ?>
                                <td><?= $this->tag->linkTo(['auctions/show/' . $task->getTaskid(), 'Тендер']) ?></td>
                            <?php } elseif ($task->status == 'Выполняется') { ?>
                                <td><?= $this->tag->linkTo(['coordination/index/' . $task->getTaskid(), 'Чат']) ?></td>
                            <?php } ?>

                        </tr>
                        <tr>
                            <?php } ?>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

<!--
<div class="row">
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Название</th>
            <th>Категория</th>
            <th>Описание</th>
            <th>Адрес</th>
            <th>Дата работ</th>
            <th>Стоимость</th>
            <th>Статус</th>

            <th colspan="2">Действия</th>
            <th>Тендер/Чат</th>
        </tr>
        </thead>
        <tbody>
        <?php if (isset($page->items)) { ?>
        <?php foreach ($page->items as $task) { ?>

        <tr>
            <td><?= $this->tag->linkTo(['auctions/show/' . $task->getTaskid(), $task->getName()]) ?></td>
            <td><?= $task->categories->getCategoryName() ?></td>
            <td><?= $task->getDescription() ?></td>
            <td><?= $task->getaddress() ?></td>
            <td><?= $task->getDeadline() ?></td>
            <td><?= $task->getPrice() ?></td>
            <td><?= $task->getStatus() ?></td>

            <td><?= $this->tag->linkTo(['tasks/editing/' . $task->getTaskid(), 'Редактировать']) ?></td>
            <td><?= $this->tag->linkTo(['tasks/delete/' . $task->getTaskid(), 'Удалить']) ?></td>
            <?php if ($task->status == 'Поиск') { ?>
            <td><?= $this->tag->linkTo(['auctions/show/' . $task->getTaskid(), 'Тендер']) ?></td>
            <?php } elseif ($task->status == 'Выполняется') { ?>
            <td><?= $this->tag->linkTo(['coordination/index/' . $task->getTaskid(), 'Чат']) ?></td>
            <?php } ?>
        </tr>
        <?php } ?>
        <?php } ?>
        </tbody>
    </table>
</div> -->
<?php if ($page->total_pages > 1) { ?>
<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?= $page->current . '/' . $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?= $this->tag->linkTo(['tasks/mytasks/' . $userId, 'Первая']) ?></li>
                <li><?= $this->tag->linkTo(['tasks/mytasks/' . $userId . '?page=' . $page->before, 'Предыдущая']) ?></li>
                <li><?= $this->tag->linkTo(['tasks/mytasks/' . $userId . '?page=' . $page->next, 'Следующая']) ?></li>
                <li><?= $this->tag->linkTo(['tasks/mytasks/' . $userId . '?page=' . $page->last, 'Последняя']) ?></li>
            </ul>
        </nav>
    </div>
</div>
<?php } ?>

<div class="tr-download-app bg-image section-padding section-before">
    <div class="container text-center">
        <h1>Загрузите в Play Маркет</h1>
        <div class="app-content">
            <div class="row">
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app1.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Google Play</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app2.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>App Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app3.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Windows Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.app-content -->
    </div><!-- /.contaioner -->
</div><!--/. tr-download-app -->
