

<?= $this->getContent();
$this->assets->outputCss();
?>



<div id="map">
    <div class="banner-form">
        <form action="#">
            <input type="text" class="form-control" placeholder="Поиск">
            <div class="dropdown tr-change-dropdown">
                <a data-toggle="dropdown" href="#" aria-expanded="false"><span class="change-text">Место</span><i class="fa fa-angle-down"></i></a>
                <ul class="dropdown-menu tr-change">

                </ul>
            </div><!-- /.category-change -->
            <button type="submit" class="btn btn-primary" value="Search">Найти</button>
        </form>
    </div><!-- /.banner-form -->
</div>


    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Список доступных тендеров</h4>
                <div class="table-responsive">
                    <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                        <thead>
                        <tr>
                            <th class="footable-sortable">№<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Заказчик<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Название<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Описание<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Адрес<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Категория<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Дата работ<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Конец тендера<span class="footable-sort-indicator"></span></th>
                            <th class="footable-sortable">Стоимость<span class="footable-sort-indicator"></span></th>
                        </tr>
                        </thead>
                        <tbody>
                        <?php $count=1; if (isset($page->items)) { ?>
                        <?php foreach ($page->items as $auction) { ?>
                        <tr>
                            <td><?=$count++; $count; ?></td>
                            <td><?= $this->tag->linkTo(['userinfo/viewprofile/' . $auction->auctions->tasks->getUserId(),
                                    '<img src="'.$auction->tasks->users->userInfo->getPathToPhoto().'" alt="user" width="40" class="img-circle"> '.$auction->auctions->tasks->users->userinfo->getFIO()])?></td>
                            <td><?= $this->tag->linkTo(['auctions/viewing/' . $auction->auctions->getAuctionid(), $auction->auctions->tasks->getName()]) ?></td>
                            <td><?= $auction->auctions->tasks->getDescription() ?></td>
                            <td><?= $auction->auctions->tasks->getaddress() ?></td>
                            <td><span class="label label-info"><?= $auction->auctions->tasks->categories->getCategoryName() ?></span></td>
                            <td><?= date('h:m d.m.Y',strtotime($auction->auctions->tasks->getDeadline())) ?></td>
                            <td><?= date('h:m d.m.Y',strtotime($auction->auctions->getDateEnd())) ?></td>
                            <td><?= $auction->auctions->tasks->getPrice() ?></td>
                        </tr>
                        <tr>
                            <?php } ?>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

    </div>

<!--

    <table class="table table-bordered">
        <thead>
        <tr>
            <th>Название</th>
            <th>Категория</th>
            <th>Описание</th>
            <th>Адрес</th>
            <th>Стоимость</th>
            <th>Конец Тендера</th>
            <th>Заказчик</th>
        </tr>
        </thead>
        <tbody>
        <?php if (isset($page->items)) { ?>
        <?php foreach ($page->items as $auction) { ?>
        <tr>
            <td><?= $this->tag->linkTo(['auctions/viewing/' . $auction->auctions->getAuctionid(), $auction->auctions->tasks->getName()]) ?></td>
            <td><?= $auction->auctions->tasks->categories->getCategoryName() ?></td>
            <td><?= $auction->auctions->tasks->getDescription() ?></td>
            <td><?= $auction->auctions->tasks->getaddress() ?></td>
            <td><?= $auction->auctions->tasks->getPrice() ?></td>
            <td><?= $auction->auctions->getDateEnd() ?></td>

            <td><?= $this->tag->linkTo(['userinfo/viewprofile/' . $auction->auctions->tasks->getUserId(), $auction->auctions->tasks->users->userinfo->getLastname()]) ?></td>

        </tr>
        <?php } ?>
        <?php } ?>
        </tbody>
    </table> -->

<?php if ($page->total_pages > 1) { ?>

    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?= $page->current . '/' . $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?= $this->tag->linkTo(['auctions/index', 'Первая']) ?></li>
                <li><?= $this->tag->linkTo(['auctions/index?page=' . $page->before, 'Предыдущая']) ?></li>
                <li><?= $this->tag->linkTo(['auctions/index?page=' . $page->next, 'Следующая']) ?></li>
                <li><?= $this->tag->linkTo(['auctions/indexs?page=' . $page->last, 'Последняя']) ?></li>
            </ul>
        </nav>
    </div>

<?php } ?>



<div class="tr-download-app bg-image section-padding section-before">
    <div class="container text-center">
        <h1>Загрузите в Play Маркет</h1>
        <div class="app-content">
            <div class="row">
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app1.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Google Play</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app2.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>App Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app3.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Windows Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.app-content -->
    </div><!-- /.contaioner -->
</div><!--/. tr-download-app -->






