<div class="tr-breadcrumb3 bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="user-title">
                <h1><?= $task->getName() ?></h1>
            </div>
            <ul class="job-meta tr-list list-inline">
                <?php
                    echo '<h3 style="color: white;"><i class="fa fa-map-marker" aria-hidden="true"></i> '.$task->getAddress().'</h3>';
                echo '<h4 style="color: white;"><i class="fa fa-clock-o" aria-hidden="true"></i> '.date('h:m d.m.Y',strtotime($task->getDeadline())).'</h4>';
                echo '<h4 style="color: white;">'.$task->getPrice(). '<i class="fa fa-rub" aria-hidden="true"></i></h4>';
                ?>
                <!--
                <li><i class="fa fa-phone" aria-hidden="true"></i>+0123 456 789</li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">jhondoe@gmail.com</a></li>
                <li><i class="fa fa-briefcase" aria-hidden="true"></i>UI & UX Designer</li>-->
            </ul>
        </div>
    </div><!-- /.container -->
</div><!-- /.tr-breadcrumb -->
<?= $this->getContent() ?>
<div id="map">
</div>



<div class="tr-profile section-padding">
    <div class="container">
        <div class="row">
            <div class=" col-md-12">

<?= $this->tag->form(['offers/new', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>
                <ul class="tr-list account-details">
                    <div class="jqte_editor" id="edit" contenteditable="false">
                        <li>Название<span><?=$task->getName()?></span></li>
                        <li>Категория<span><?= $task->categories->getCategoryName() ?></span></li>
                        <li>Описание<span><?= $task->getDescription() ?> </span></li>
                        <li>Адрес<span id="fieldaddress"><?=$task->getAddress()?></span></li>
                        <li>Дата работ<span><?= date('h:m d.m.Y',strtotime($task->getDeadline())) ?></span></li>
                        <li>Стоимость<span><?=$task->getPrice()?></span></li>
                        <li>Дата начала тендера<span><?=date('h:m d.m.Y',strtotime($auction->getDateStart()))?></span></li>
                        <li>Дата окончания тендера<span><?=date('h:m d.m.Y',strtotime($auction->getDateEnd()))?></span></li>
                        <li>Координаты<span id="fieldCoord"><?=$task->getLatitude().','.$task->getLongitude()?></span></li>
                </ul>
                </form>


<!--
<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Название</label>
    <div class="col-sm-10">
        <?= $task->getName() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategoryid" class="col-sm-2 control-label">Категория</label>
    <div class="col-sm-10">
        <?= $task->categories->getCategoryName() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Описание</label>
    <div class="col-sm-10">
        <?= $task->getDescription() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldaddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $task->getAddress() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDeadline" class="col-sm-2 control-label">Дата работ</label>
    <div class="col-sm-10">
        <?= $task->getDeadline() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Стоимость</label>
    <div class="col-sm-10">
        <?= $task->getPrice() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatestart" class="col-sm-2 control-label">Дата начала тендера</label>
    <div class="col-sm-10">
        <?= $auction->getDateStart() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateend" class="col-sm-2 control-label">Дата окончания тендера</label>
    <div class="col-sm-10">
        <?= $auction->getDateEnd() ?>
    </div>
</div>
</form>
-->
                <div class="card-body">
                    <h4 class="card-title">Список откликнувшихся исполнителей</h4>
                    <div class="table-responsive">
                        <table id="demo-foo-addrow" class="table m-t-30 table-hover contact-list" data-page-size="10">
                            <thead>
                            <tr>
                                <th class="footable-sortable">№<span class="footable-sort-indicator"></span></th>
                                <th class="footable-sortable">Исполнитель<span class="footable-sort-indicator"></span></th>
                                <th class="footable-sortable">Срок<span class="footable-sort-indicator"></span></th>
                                <th class="footable-sortable">Описание<span class="footable-sort-indicator"></span></th>
                                <th class="footable-sortable">Стоимость<span class="footable-sort-indicator"></span></th>
                                <th class="footable-sortable">Score<span class="footable-sort-indicator"></span></th>
                                <th class="footable-sortable">Действия<span class="footable-sort-indicator"></span></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $count=1; if (isset($page->items)) { ?>
                            <?php foreach ($page->items as $offer) { ?>
                            <tr>
                                <td><?=$count++; $count; ?></td>
                                <td><?= $this->tag->linkTo(['userinfo/viewprofile/' .  $offer->getUserId(),
                                        '<img src="'.$offer->users->userinfo->getPathToPhoto().'" alt="user" width="40" class="img-circle"> '. $offer->users->userinfo->getFIO()])?></td>
                                <td><?= date('h:m d.m.Y',strtotime($offer->getDeadline()))?></td>
                                <td><?= $offer->getDescription() ?></td>
                                <td><?= $offer->getPrice() ?></td>
                                <td><?= $offer->getScore() ?></td>
                                <td><?= $this->tag->linkTo(['auctions/choice/' . $offer->getOfferId(), 'Выбрать']) ?></td>
                            </tr>
                            <tr>
                                <?php } ?>
                                <?php } ?>
                            </tbody>
                        </table>
                    </div>
                </div>


<?php if ($page->total_pages > 1) { ?>
<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?= $page->current . '/' . $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?= $this->tag->linkTo(['auctions/search', 'Первая']) ?></li>
                <li><?= $this->tag->linkTo(['auctions/search?page=' . $page->before, 'Предыдущая']) ?></li>
                <li><?= $this->tag->linkTo(['auctions/search?page=' . $page->next, 'Следующая']) ?></li>
                <li><?= $this->tag->linkTo(['auctions/search?page=' . $page->last, 'Последняя']) ?></li>
            </ul>
        </nav>
    </div>
</div>
<?php } ?>
            </div>
        </div>
    </div>
</div>


<div class="tr-download-app bg-image section-padding section-before">
    <div class="container text-center">
        <h1>Загрузите в Play Маркет</h1>
        <div class="app-content">
            <div class="row">
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app1.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Google Play</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app2.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>App Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app3.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Windows Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.app-content -->
    </div><!-- /.contaioner -->
</div><!--/. tr-download-app -->
