
<div class="tr-breadcrumb3 bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="user-title">
                <h1><?= $task->getName() ?></h1>
            </div>
            <ul class="job-meta tr-list list-inline">
                <?php
                    echo '<h3 style="color: white;"><i class="fa fa-map-marker" aria-hidden="true"></i> '.$task->getAddress().'</h3>';
                echo '<h4 style="color: white;"><i class="fa fa-clock-o" aria-hidden="true"></i> '.date('h:m d.m.Y',strtotime($task->getDeadline())).'</h4>';
                echo '<h4 style="color: white;">'.$task->getPrice(). '<i class="fa fa-rub" aria-hidden="true"></i></h4>';
                ?>
                <!--
                <li><i class="fa fa-phone" aria-hidden="true"></i>+0123 456 789</li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">jhondoe@gmail.com</a></li>
                <li><i class="fa fa-briefcase" aria-hidden="true"></i>UI & UX Designer</li>-->
            </ul>
        </div>
    </div><!-- /.container -->
</div><!-- /.tr-breadcrumb -->
<?= $this->getContent() ?>
<div id="map">
</div>



<div class="tr-profile section-padding">
    <div class="container">
        <div class="row">
            <div class=" col-md-12">

                <?= $this->tag->form(['offers/new', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>
                <ul class="tr-list account-details">
                <div class="jqte_editor" id="edit" contenteditable="false">
                    <li>Название<span><?=$task->getName()?></span></li>
                    <li>Категория<span><?= $task->categories->getCategoryName() ?></span></li>
                    <li>Описание<span><?= $task->getDescription() ?> </span></li>
                    <li>Адрес<span id="fieldaddress"><?=$task->getAddress()?></span></li>
                    <li>Дата работ<span><?= date('h:m d.m.Y',strtotime($task->getDeadline())) ?></span></li>
                    <li>Стоимость<span><?=$task->getPrice()?></span></li>
                    <li>Дата начала тендера<span><?=date('h:m d.m.Y',strtotime($auction->getDateStart()))?></span></li>
                    <li>Дата окончания тендера<span><?=date('h:m d.m.Y',strtotime($auction->getDateEnd()))?></span></li>
                    <li>Координаты<span id="fieldCoord"><?=$task->getLatitude().','.$task->getLongitude()?></span></li>

                    <div style="margin-top: 15px;"><?= $this->tag->submitButton(['Вступить', 'class' => 'btn btn-primary']) ?>
                     <?= $this->tag->linkTo(['userinfo/viewprofile/' . $auction->tasks->getUserId(), 'Профиль', 'class' => 'btn btn-primary', 'style'=>'margin-left: 15px;']) ?></div>
                </div>
                </ul>
                </form>
<!--
<?= $this->tag->form(['offers/new', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Название</label>
    <div class="col-sm-10">
        <?= $task->getName() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCategoryid" class="col-sm-2 control-label">Категория</label>
    <div class="col-sm-10">
        <?= $task->categories->getCategoryName() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDescription" class="col-sm-2 control-label">Описание</label>
    <div class="col-sm-10">
        <?= $task->getDescription() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldaddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10" id="fieldaddress">
        <?= $task->getAddress() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDeadline" class="col-sm-2 control-label">Дата работ</label>
    <div class="col-sm-10">
        <?= date('h:m d.m.Y',strtotime($task->getDeadline())) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPrice" class="col-sm-2 control-label">Стоимость</label>
    <div class="col-sm-10">
        <?= $task->getPrice() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDatestart" class="col-sm-2 control-label">Дата начала тендера</label>
    <div class="col-sm-10">
        <?= date('h:m d.m.Y',strtotime($auction->getDateStart())) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldDateend" class="col-sm-2 control-label">Дата окончания тендера</label>
    <div class="col-sm-10">
        <?= date('h:m d.m.Y',strtotime($auction->getDateEnd())) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldCoord" class="col-sm-2 control-label">Координаты</label>
    <div class="col-sm-10" id="fieldCoord">
        <?= $task->getLatitude().','.$task->getLongitude()?>
    </div>
</div>


<div class="buttons pull-right">
<div class="form-group">
    <div class="col-md-3">
        <?= $this->tag->submitButton(['Вступить', 'class' => 'btn btn-primary']) ?>
    </div>
</div>

<div class="form-group">
    <div class="col-md-3">
        <?= $this->tag->linkTo(['userinfo/viewprofile/' . $auction->tasks->getUserId(), 'Профиль', 'class' => 'btn btn-primary']) ?>
    </div>
</div>
</div>
</form>-->

            </div>
        </div>
    </div>
</div>


<div class="tr-download-app bg-image section-padding section-before">
    <div class="container text-center">
        <h1>Загрузите в Play Маркет</h1>
        <div class="app-content">
            <div class="row">
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app1.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Google Play</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app2.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>App Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="download-app">
                        <a href="#">
                            <div class="download-image">
                                <img src="/images/icons/app3.png" alt="Image" class="img-responsive">
                            </div>
                            <div class="download-info">
                                <span>Доступно в</span>
                                <strong>Windows Store</strong>
                            </div>
                        </a>
                    </div>
                </div>
            </div><!-- /.row -->
        </div><!-- /.app-content -->
    </div><!-- /.contaioner -->
</div><!--/. tr-download-app -->


