
<?= $this->getContent() ?>

<body>
<div class="tr-breadcrumb bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="page-title">
                <h1>Регистрация нового аккаунта</h1>
            </div>
        </div>
    </div><!-- /.container -->
</div><!-- tr-breadcrumb -->
<div class="tr-account section-padding">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="user-account">
                            <div class="account-content">
                                <?= $this->tag->form(['register', 'id' => 'registerForm', 'onbeforesubmit' => 'return false']) ?>
                                    <div class="form-group">
                                        <input name="firstname" type="text" class="form-control" placeholder="Имя">
                                    </div>
                                    <div class="form-group">
                                        <input name="lastname" type="text" class="form-control" placeholder="Фамилия">
                                    </div>
                                    <div class="form-group">
                                        <input name="phone" type="text" class="form-control" placeholder="Номер телефона">
                                    </div>
                                    <div class="form-group">
                                        <input name="email" type="email" class="form-control" placeholder="Email">
                                    </div>
                                    <div class="form-group">
                                        <input name="password" type="password" class="form-control" placeholder="Пароль">
                                    </div>
                                    <div class="form-group">
                                        <input name="repeatPassword" type="password" class="form-control" placeholder="Подтвердите пароль">
                                    </div>
                                   <!-- <div class="dropdown tr-change-dropdown"> -->
                                        <div class="form-group">
                                        <?php $element=$form->getElements()['male'];
                                        $element->label(['class' => 'form-control']);?>

                                                <?=$element?>


                                     <!--   <a data-toggle="dropdown" href="#" aria-expanded="false"><span  class="change-text">Пол</span><i class="fa fa-angle-down"></i></a>
                                        <ul name="male" class="dropdown-menu tr-change">
                                            <li><a href="#">Мужской</a></li>
                                            <li><a href="#">Женский</a></li>
                                        </ul>-->
                                    </div><!-- /.category-change -->
                                <?= $this->tag->submitButton(['Зарегистрироваться', 'class' => 'btn btn-primary', 'onclick' => 'return SignUp.validate();']) ?>
                                <p class="help-block">Регистрируясь, вы соглашаетесь с правилами сайта и пользовательским соглашением</p>
                                </form>
                                <div class="new-user text-center">
                                    <span>Уже зарегистрированы? <a href="/session/index">Войти</a> </span>
                                </div>
                            </div>
                        </div>
            </div>
        </div><!-- /.row -->
    </div><!-- container -->
</div><!-- /.tr-account-->
</body>
<!--
<div class="page-header">
    <h2>Регистрация</h2>
</div>

<?= $this->tag->form(['register', 'id' => 'registerForm', 'onbeforesubmit' => 'return false']) ?>

<fieldset>

    <?php foreach ($form as $element) { ?>
    <div class="control-group">
        <?= $element->label(['class' => 'control-label']) ?>

        <div class="control">
            <?= $element ?>
        </div>
    </div>
    <?php } ?>
    <div class="form-actions">
        <?= $this->tag->submitButton(['Регистрация', 'class' => 'btn btn-primary', 'onclick' => 'return SignUp.validate();']) ?>

    </div>



</fieldset>
</form>
-->