

<?php $this->assets->outputJs(); ?>
<?= $this->getContent() ?>

<div class="tr-breadcrumb bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="user-image">
                <img src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="Image" class="img-responsive">
            </div>
            <div class="user-title">
                <h1><?= $userinfo->getLastName().' '.$userinfo->getFirstname().' '.$userinfo->getPatronymic() ?></h1>
            </div>
            <ul class="job-meta tr-list list-inline">
                <?php
                    if(!empty($userinfo->getAddress()))
                     echo '<li><i class="fa fa-map-marker" aria-hidden="true"></i>'.$userinfo->getAddress().'</li>';
                        ?>
                <!--
                <li><i class="fa fa-phone" aria-hidden="true"></i>+0123 456 789</li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">jhondoe@gmail.com</a></li>
                <li><i class="fa fa-briefcase" aria-hidden="true"></i>UI & UX Designer</li>-->
            </ul>
        </div>
    </div><!-- /.container -->
</div><!-- /.tr-breadcrumb -->


    <div class="tr-profile section-padding">
        <div class="container">
            <div class="row">
                <div class="col-sm-4 col-md-3">
                    <div class="tr-sidebar">
                        <ul class="nav nav-tabs profile-tabs section" role="tablist">
                          <!-- <li role="presentation" class="active"><a href="#account-info" aria-controls="account-info" role="tab" data-toggle="tab"><i class="fa fa-life-ring" aria-hidden="true"></i> Профиль</a></li>-->
                            <li role="presentation" class="active"><a href="#account-info" aria-controls="account-info" role="tab" data-toggle="tab"><span><i class="fa fa-user-o" aria-hidden="true"></i></span> Профиль</a></li>
                            <li role="presentation"><a href="#account-settings" aria-controls="account-settings" role="tab" data-toggle="tab"><span><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span> Настройки</a></li>
                            <li role="presentation"><a href="#bookmark" aria-controls="bookmark" role="tab" data-toggle="tab"><span><i class="fa fa-bookmark-o" aria-hidden="true"></i></span> Любимые категории</a></li>
                            <!--  <li role="presentation"><a href="#archived" aria-controls="archived" role="tab" data-toggle="tab"><span><i class="fa fa-clone" aria-hidden="true"></i></span> Archived Apply Job</a></li>
                              <li role="presentation"><a href="#close-account" aria-controls="close-account" role="tab" data-toggle="tab"><span><i class="fa fa-scissors" aria-hidden="true"></i></span> Close Account</a></li>-->
                          </ul>
                      </div><!-- /.tr-sidebar -->
                </div>
                <div class="col-sm-8 col-md-9">
                    <div class="tab-content">
                        <div role="tabpanel" class="tab-pane fade in active account-info" id="account-info">
                            <div class="tr-fun-fact">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="fun-fact">
                                            <div class="fun-fact-icon">
                                                <img src="/images/icons/fun-fact4.png" alt="images" class="img-responsive">
                                            </div>
                                            <div class="media-body">
                                                <h1 class="counter"><?php echo count($userinfo->users->tasks); ?></h1>
                                                <span>Размещенных заданий</span>
                                            </div>
                                        </div><!-- /.fun-fact -->
                                    </div>
                                   <!-- <div class="col-sm-4">
                                        <div class="fun-fact">
                                            <div class="fun-fact-icon">
                                                <img src="/images/icons/fun-fact5.png" alt="images" class="img-responsive">
                                            </div>
                                            <div class="media-body">
                                                <h1 class="counter">32</h1>
                                                <span>Выполненных заданий</span>
                                            </div>
                                        </div>
                                    </div>-->
                                    <div class="col-sm-4">
                                        <div class="fun-fact">
                                            <div class="fun-fact-icon">
                                                <img src="/images/icons/fun-fact6.png" alt="images" class="img-responsive">
                                            </div>
                                            <div class="media-body">
                                                <h1 class="counter"><?php echo count($reviews['owner']) ?></h1>
                                                <span>Отзывов на пользователя</span>
                                            </div>
                                        </div><!-- /.fun-fact -->
                                    </div>
                                </div><!-- ./row -->
                            </div><!-- /.tr-fun-fact -->

                            <div class="section display-information">
                                <div class="title title-after">
                                    <div class="icon"><img src="/images/icons/2.png" alt="Icon" class="img-responsive"></div>
                                    <span>Публичная информация</span>
                                </div>

                                <div class="change-photo">
                                    <div class="user-image">
                                        <div class="image-preview">
                                        <img id="preview" src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="Image" class="img-responsive">
                                        </div>
                                    </div>
                                   <!-- <div class="col-md-6 col-md-offset-3">
                                                <div class="image-preview">
                                                    <img id="preview" src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="">
                                                </div>
                                                <form id="upload-image" enctype="multipart/form-data">
                                                    <div class="form-group">
                                                        <input type="file" name="image" id="image">
                                                    </div>
                                                    <input type="submit" class="btn btn-default" id="btnImg">
                                                </form>
                                                <div id="result">
                                                </div>
                                            </div>-->
                                    <form id="upload-image" enctype="multipart/form-data">
                                    <div class="upload-photo" >
                                        <label class="btn btn-primary" for="image">
                                            <input type="file" name="image" id="image">
                                            Изменить фото
                                        </label>
                                        <span class="max-size">Max 5 MB</span>
                                        <label class="btn btn-primary" for="btnImg">
                                        <input type="submit" class="btn btn-default" id="btnImg">
                                        Загрузить</label>
                                    </div>
                                    </form>

                                    <form method="get" action="/Companies/index">
                                        <button type="submit" class="btn btn-primary col-md-4" id="save" style="margin-left: 15px;">К компаниям</button>
                                    </form>

                                </div>
                                <form method="post" action="/userinfo/save">
                                <ul class="tr-list account-details">
                                    <div class="jqte_editor" id="edit" contenteditable="false">

                                    <li>Фамилия <input name='lastname' id="lastname"value="<?= $userinfo->getLastName()?>"></li>
                                    <li>Имя <input type="text" name='firstname' id="firstname" value="<?= $userinfo->getFirstName() ?>"></li>
                                    <li>Отчество <input type="text" name='patronymic' id="patronymic" value="<?= $userinfo->getPatronymic() ?>"></li>
                                    <li>Адрес <input type="text" name='address' id="address" value="<?= $userinfo->getAddress() ?>"></li>
                                    <li>Дата рождения <?= $this->tag->dateField(['birthday', 'class' => 'form-control', 'id' => 'fieldBirthday']) ?></li>
                                    <li>Пол <?= $this->tag->selectStatic(['male', ['1' => 'Мужской', '0' => 'Женский'], 'class' => 'form-control', 'id' => 'fieldMale']) ?></li>
                                    <!--TODO чтобы текст выводился полностью со всеми переносами строк-->
                                    <li>О себе<?= $this->tag->textArea(['about', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAbout']) ?></li>
                                    </div>
                                   <li> <button type="submit" class="btn btn-primary col-md-4" id="save" style="margin-left: 15px;">Сохранить</button></li>
                                </form>
                                    <!--TODO чтобы рейтинг заполнялся из бд-->
                                    <li class="language-proficiency code-edit-small" id="rating" style="margin-top: 15px;">
                                        <div class="media-body">
                                            <div class="rating-star">
                                                <span class="pull-left code-edit">Рейтинг исполнителя</span>
                                                <div class="rating">
                                                    <?php $this->elements->getRating('Executor',$userinfo->getRaitingExecutor())?>
                                                </div>
                                            </div>
                                            <div class="rating-star">
                                                <span class="pull-left code-edit">Рейтинг заказчика</span>
                                                <div class="rating">
                                                    <?php $this->elements->getRating('Client',$userinfo->getRaitingClient())?>
                                                </div>
                                            </div>
                                        </div>
                                    </li><!-- /.language-proficiency -->
                                </ul>
                               <!-- <button type="button" class="btn btn-primary col-md-4" id="change">Изменить</button>-->

                            </div><!-- /.display-information -->
                            <div class="section display-information">
                                <div class="title ">
                                    <span class="tr-title">Отзывы</span>
                                </div>
                                <div class="media-body work-history">
                                    <div class="comment-widgets m-b-20">
                                        <ul class="tr-list">
                                            <?php
                                            for($i=0;$i<count($reviews['owner']);$i++)
                                            {
                                                echo "<li>
                                                <div class=\"d-flex flex-row comment-row\">
                                                <div class=\"p-2\"><span class=\"round\"><img src=\"".$reviews['avatar'][$i]."   \" alt=\"user\" width=\"50\"></span></div>
                                                 <div class=\"comment-text w-100\">
                                                 <h5>".$reviews['owner'][$i]."</h5>
                                                 <div class=\"comment-footer\">
                                                 <span class=\"date\">".$reviews['date'][$i]."</span>
                                                 </div>
                                                  <p class=\"m-b-5 m-t-10\">".$reviews['text'][$i]."</p>
                                                </div>
                                                
                                                <div class=\"rating-star\">
                                                <span class=\"pull-left code-edit\">Рейтинг ".$reviews['role'][$i]."</span>
                                                <div class=\"rating\">";
                                                $this->elements->getRating('',$reviews['raiting'][$i]);
                                                echo "
                                                </div>
                                            </div>
                                            </div>
                                             </li>";

                                            }
                                            ?>
                                        </ul>
                        </div>
                    </div>
                        </div>
                        </div>

                        <div role="tabpanel" class="tab-pane account-settings section" id="account-setting">
                                <div class="row">
                                    <div class="col-sm-4">
                                        <div class="section display-information">
                                        <h1>ho</h1>
                                        </div>
                                    </div>
                                </div>
                        </div>
                </div>
                </div>
            </div>
        </div>
    </div>

<!--
<script type="text/javascript">
    $( document ).ready(function () {
        $('#change').click(function () {
            if($('#change').text()=='Изменить')
            {
                $('#edit').prop('contenteditable','true');
                $('#change').text('Отмена');
                $('#save').show();
                $('#rating').hide();
            }
            else
            {
                $('#edit').prop('contenteditable','false');
                $('#change').text('Изменить');
                $('#save').hide();
                $('#rating').show();
            }
        })
    })
</script>
-->
<!--
<?= $this->tag->form(['userinfo/save', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>
<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['firstname', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldFirstname', 'onclick' => 'return SignUp.validate();']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPatronymic" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['patronymic', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldPatronymic']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['lastname', 'size' => 30, 'class' => 'form-control', 'id' => 'fieldLastname']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBirthday" class="col-sm-2 control-label">Дата рождения</label>
    <div class="col-sm-10">
        <?= $this->tag->dateField(['birthday', 'class' => 'form-control', 'id' => 'fieldBirthday']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMale" class="col-sm-2 control-label">Пол</label>
    <div class="col-sm-10">
        <?= $this->tag->selectStatic(['male', ['1' => 'Мужской', '0' => 'Женский'], 'class' => 'form-control', 'id' => 'fieldMale']) ?>

    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['address', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAddress']) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAbout" class="col-sm-2 control-label">О себе</label>
    <div class="col-sm-10">
        <?= $this->tag->textArea(['about', 'cols' => '30', 'rows' => '4', 'class' => 'form-control', 'id' => 'fieldAbout']) ?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRaitingExecutor" class="col-sm-2 control-label">Рейтинг исполнителя</label>
    <div class="col-sm-10">
        <?= $userinfo->getRaitingExecutor();/*$this->tag->numericField(['raitingExecutor', 'min' => '0', 'max'=>'10', 'class' => 'form-control', 'id' => 'fieldRaitingExecutor']) */?>
    </div>
</div>
<div class="form-group">
    <label for="fieldRaitingClient" class="col-sm-2 control-label">Рейтинг заказчика</label>
    <div class="col-sm-10">
        <?= $userinfo->getRaitingClient();// $this->tag->numericField(['raitingClient', 'min' => '0', 'max'=>'10', 'class' => 'form-control', 'id' => 'fieldRaitingClient']) ?>
    </div>
</div> -->
<!--<div class="form-group">
    <label for="fieldPathToPhoto" class="col-sm-2 control-label">Путь к изображению профиля</label>
    <div class="col-sm-10">
        <?= $this->tag->textField(['pathToPhoto', 'length'=>'260', 'class' => 'form-control', 'id' => 'fieldPathToPhoto']) ?>
    </div>
</div>-->
<!--<div class="form-group">
    <div class="col-md-6 col-md-offset-3">
        <img src=
            <?php
            echo '"'.$userinfo->getPathToPhoto().'"';
            ?>
        >
    </div>
</div>-->



<!--
<div class="form-group">
    <label for="fieldExecutor" class="col-sm-2 control-label">Исполнитель</label>
    <div class="col-sm-10">
          <input type="checkbox" name="executor" onclick="<script type='text/javascript'{if (this.checked == true){this.checked=false}; else {this.checked=true};}/>"
          />
        <!--   <script>
            $("checkbox").on("click", function () {
                if($(this).attr("checked")==true){
                    $(this).attr("checked","false");
                    $(this).attr("value","1");

                }else {
                    $(this).attr("checked", "true");
                    $(this).attr("value","1");
                }
            })
        </script>



    </div>
</div>
-->



<!--<?= $this->tag->hiddenField(['id']) ?>-->
<!--
<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?= $this->tag->submitButton(['Сохранить', 'class' => 'btn btn-default']) ?>
    </div>
</div>


</form>

-->