


<?= $this->getContent() ?>


<div class="tr-breadcrumb bg-image section-before">
    <div class="container">
        <div class="breadcrumb-info text-center">
            <div class="user-image">
                <img src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="Image" class="img-responsive">
            </div>
            <div class="user-title">
                <h1><?= $userinfo->getLastName().' '.$userinfo->getFirstname().' '.$userinfo->getPatronymic() ?></h1>
            </div>
            <ul class="job-meta tr-list list-inline">
                <?php
                if(!empty($userinfo->getAddress()))
                    echo '<li><i class="fa fa-map-marker" aria-hidden="true"></i>'.$userinfo->getAddress().'</li>';
                ?>
                <!--
                <li><i class="fa fa-phone" aria-hidden="true"></i>+0123 456 789</li>
                <li><i class="fa fa-envelope" aria-hidden="true"></i><a href="#">jhondoe@gmail.com</a></li>
                <li><i class="fa fa-briefcase" aria-hidden="true"></i>UI & UX Designer</li>-->
            </ul>
        </div>
    </div><!-- /.container -->
</div><!-- /.tr-breadcrumb -->


<div class="tr-profile section-padding">
    <div class="container">
        <div class="row">
            <div class=" col-md-12">
                <div class="tab-content">
                    <div role="tabpanel" class="tab-pane fade in active account-info" id="account-info">
                        <div class="tr-fun-fact">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="fun-fact">
                                        <div class="fun-fact-icon">
                                            <img src="/images/icons/fun-fact4.png" alt="images" class="img-responsive">
                                        </div>
                                        <div class="media-body">
                                            <h1 class="counter">39</h1>
                                            <span>Размещенных заданий</span>
                                        </div>
                                    </div><!-- /.fun-fact -->
                                </div>
                                <div class="col-sm-4">
                                    <div class="fun-fact">
                                        <div class="fun-fact-icon">
                                            <img src="/images/icons/fun-fact5.png" alt="images" class="img-responsive">
                                        </div>
                                        <div class="media-body">
                                            <h1 class="counter">32</h1>
                                            <span>Выполненных заданий</span>
                                        </div>
                                    </div><!-- /.fun-fact -->
                                </div>
                                <div class="col-sm-4">
                                    <div class="fun-fact">
                                        <div class="fun-fact-icon">
                                            <img src="/images/icons/fun-fact6.png" alt="images" class="img-responsive">
                                        </div>
                                        <div class="media-body">
                                            <h1 class="counter">27</h1>
                                            <span>Отзывов</span>
                                        </div>
                                    </div><!-- /.fun-fact -->
                                </div>
                            </div><!-- ./row -->
                        </div><!-- /.tr-fun-fact -->

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
                            </div>
                        </div>

                        <div class="section display-information">

                            <div class="title title-after">
                                <div class="icon"><img src="/images/icons/2.png" alt="Icon" class="img-responsive"></div>
                                <span>Профиль пользователя</span>
                            </div>

                                <div class="user-image">
                                    <img id="preview" src=<?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="Image" class="img-responsive">
                                </div>

                            <ul class="tr-list account-details">
                                <div class="jqte_editor" id="edit" contenteditable="false">
                                    <li>ФИО<span><?= $userinfo->getLastName().' '.$userinfo->getFirstname().' '.$userinfo->getPatronymic() ?></span></li>

                                    <li>Адрес<span><?= $userinfo->getAddress() ?></span></li>
                                    <li>Дата рождения<span>
                                            <?php
                                            $birthday=date('h:i d:m:Y',strtotime($userinfo->getBirthday()));
                                            echo $birthday;
                                            ?>
                                        </span></li>
                                    <li>Пол<span><?=$userinfo->getMale()?></span></li>
                                    <!--TODO чтобы текст выводился полностью со всеми переносами строк-->
                                    <li>О себе<span><?= $userinfo->getAbout() ?></span></li>
                                </div>
                                <!--TODO чтобы рейтинг заполнялся из бд-->
                                <li class="language-proficiency code-edit-small" style="margin-top: 15px;">
                                    <div class="media-body">
                                        <div class="rating-star">
                                            <span class="pull-left code-edit">Рейтинг исполнителя</span>
                                            <div class="rating">
                                                <input type="radio" checked ="star1" name="rating" /><label class = "full" for="star1"></label>

                                                <input type="radio" checked id="star2" name="rating"/><label class="half" for="star2"></label>

                                                <input type="radio" checked id="star3" name="rating"/><label class ="full" for="star3"></label>

                                                <input type="radio" checked id="star4" name="rating"/><label class="half" for="star4"></label>

                                                <input type="radio" id="star5" name="rating"/><label class ="full" for="star5"></label>

                                                <input type="radio" id="star6" name="rating"/><label class="half" for="star6"></label>

                                                <input type="radio" id="star7" name="rating"/><label class ="full" for="star7"></label>

                                                <input type="radio" id="star8" name="rating"/><label class="half" for="star8"></label>

                                                <input type="radio" id="star9" name="rating"/><label class ="full" for="star9"></label>

                                                <input type="radio" id="star10" name="rating"/><label class="half" for="star10"></label>
                                            </div>
                                        </div>
                                        <div class="rating-star">
                                            <span class="pull-left code-edit">Рейтинг заказчика</span>
                                            <div class="rating">
                                                <input type="radio"  checked id="star11" name="rating1" /><label class = "full" for="star11"></label>

                                                <input type="radio"  id="star12" name="rating1"/><label class="half" for="star12"></label>

                                                <input type="radio"  id="star13" name="rating1"/><label class ="full" for="star13"></label>

                                                <input type="radio"  id="star14" name="rating1"/><label class="half" for="star14"></label>

                                                <input type="radio"  id="star15" name="rating1"/><label class ="full" for="star15"></label>

                                                <input type="radio"  id="star16" name="rating1"/><label class="half" for="star16"></label>

                                                <input type="radio"  id="star17" name="rating1"/><label class ="full" for="star17"></label>

                                                <input type="radio"  id="star18" name="rating1"/><label class="half" for="star18"></label>

                                                <input type="radio"   id="star19" name="rating1"/><label class ="full" for="star19"></label>

                                                <input type="radio"  id="star20" name="rating1"/><label class="half" for="star20"></label>
                                            </div>
                                        </div>
                                    </div>
                                </li><!-- /.language-proficiency -->
                            </ul>
                        </div><!-- /.display-information -->
                    </div>
                </div>

                <div class="section display-information">
                    <div class="title ">
                        <span class="tr-title">Отзывы</span>
                    </div>
                    <div class="media-body work-history">
                        <div class="comment-widgets m-b-20">
                            <ul class="tr-list">
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/1.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>James Anderson</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row ">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/2.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text active w-100">
                                            <h5>Michael Jorden</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/3.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>Johnathan Doeting</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry.</p>
                                        </div>
                                    </div>
                                </li>
                                <li>
                                    <!-- Comment Row -->
                                    <div class="d-flex flex-row comment-row">
                                        <div class="p-2"><span class="round"><img src="/assets/images/users/4.jpg" alt="user" width="50"></span></div>
                                        <div class="comment-text w-100">
                                            <h5>James Anderson</h5>
                                            <div class="comment-footer">
                                                <span class="date">April 14, 2016</span>
                                            </div>
                                            <p class="m-b-5 m-t-10">Lorem Ipsum is simply dummy text of the printing and type setting industry. Lorem Ipsum has beenorem Ipsum is simply dummy text of the printing and type setting industry</p>
                                        </div>
                                    </div>
                                </li>

                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>



<!--

<?= $this->tag->form(['userinfo/save', 'method' => 'post', 'autocomplete' => 'off', 'class' => 'form-horizontal']) ?>



<div class="form-group">
    <label for="fieldFirstname" class="col-sm-2 control-label">Имя</label>
    <div class="col-sm-10">
        <?= $userinfo->getFirstname() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldPatronymic" class="col-sm-2 control-label">Отчество</label>
    <div class="col-sm-10">
        <?= $userinfo->getPatronymic() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldLastname" class="col-sm-2 control-label">Фамилия</label>
    <div class="col-sm-10">
        <?= $userinfo->getLastname() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldBirthday" class="col-sm-2 control-label">Дата рождения</label>
    <div class="col-sm-10">
        <?= $userinfo->getBirthday() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldMale" class="col-sm-2 control-label">Пол</label>
    <div class="col-sm-10">
        <?= $userinfo->getMale() ?>

    </div>
</div>

<div class="form-group">
    <label for="fieldAddress" class="col-sm-2 control-label">Адрес</label>
    <div class="col-sm-10">
        <?= $userinfo->getAddress() ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldAbout" class="col-sm-2 control-label">О себе</label>
    <div class="col-sm-10">
        <?= $userinfo->getAbout() ?>
    </div>
</div>


<div class="image-preview">
    <img id="preview" src= <?= '"'.$userinfo->getPathToPhoto().'"' ?> alt="">
</div>


</form>
-->