<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["companies", "Go Back"]) ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>
        Create companies
    </h1>
</div>

<?php echo $this->getContent(); ?>

<?php
    echo $this->tag->form(
        [
            "Companies/create",
            "autocomplete" => "off",
            "method" => "POST",
            "class" => "form-horizontal"
        ]
    );
?>

<div class="form-group">
    <label for="fieldName" class="col-sm-2 control-label">Name</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["name", "size" => 30, "class" => "form-control", "id" => "fieldName"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFullname" class="col-sm-2 control-label">FullName</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fullName", "size" => 30, "class" => "form-control", "id" => "fieldFullname"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldTin" class="col-sm-2 control-label">TIN</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["TIN", "size" => 30, "class" => "form-control", "id" => "fieldTin"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldContactdetails" class="col-sm-2 control-label">ContactDetails</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["contactDetails", "type" => "number", "class" => "form-control", "id" => "fieldContactdetails"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldRegion" class="col-sm-2 control-label">Region</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["region", "size" => 30, "class" => "form-control", "id" => "fieldRegion"]) ?>
    </div>
</div>


<div class="form-group">
    <label for="fieldEmail" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["email", "size" => 30, "class" => "form-control", "id" => "fieldEmail"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldFax" class="col-sm-2 control-label">Fax</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["fax", "size" => 30, "class" => "form-control", "id" => "fieldFax"]) ?>
    </div>
</div>

<div class="form-group">
    <label for="fieldWebsite" class="col-sm-2 control-label">WebSite</label>
    <div class="col-sm-10">
        <?php echo $this->tag->textField(["webSite", "size" => 30, "class" => "form-control", "id" => "fieldWebsite"]) ?>
    </div>
</div>


<div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
        <?php echo $this->tag->submitButton(["Save", "class" => "btn btn-default"]) ?>
    </div>
</div>

<?php echo $this->tag->endForm(); ?>
