<?php
/**
 * @var \Phalcon\Mvc\View\Engine\Php $this
 */
?>

<?php use Phalcon\Tag; ?>

<div class="row">
    <nav>
        <ul class="pager">
            <li class="previous"><?php echo $this->tag->linkTo(["companies/index", "Go Back"]); ?></li>
            <li class="next"><?php echo $this->tag->linkTo(["companies/new", "Create "]); ?></li>
        </ul>
    </nav>
</div>

<div class="page-header">
    <h1>Search result</h1>
</div>

<?php echo $this->getContent(); ?>

<div class="row">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>CompanyId</th>
            <th>Name</th>
            <th>FullName</th>
            <th>TIN</th>
            <th>Region</th>
            <th>UserId</th>

                <th></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
        <?php foreach ($page->items as $companie): ?>
            <tr>
                <td><?php echo $companie->getCompanyid() ?></td>
            <td><?php echo $companie->getName() ?></td>
            <td><?php echo $companie->getFullname() ?></td>
            <td><?php echo $companie->getTin() ?></td>
            <td><?php echo $companie->getRegion() ?></td>
            <td><?php echo $companie->getUserid() ?></td>

                <td><?php echo $this->tag->linkTo(["companies/edit/" . $companie->getCompanyid(), "Edit"]); ?></td>
                <td><?php echo $this->tag->linkTo(["companies/delete/" . $companie->getCompanyid(), "Delete"]); ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
</div>

<div class="row">
    <div class="col-sm-1">
        <p class="pagination" style="line-height: 1.42857;padding: 6px 12px;">
            <?php echo $page->current, "/", $page->total_pages ?>
        </p>
    </div>
    <div class="col-sm-11">
        <nav>
            <ul class="pagination">
                <li><?php echo $this->tag->linkTo("companies/search", "First") ?></li>
                <li><?php echo $this->tag->linkTo("companies/search?page=" . $page->before, "Previous") ?></li>
                <li><?php echo $this->tag->linkTo("companies/search?page=" . $page->next, "Next") ?></li>
                <li><?php echo $this->tag->linkTo("companies/search?page=" . $page->last, "Last") ?></li>
            </ul>
        </nav>
    </div>
</div>
